- config.go
- main.go
- mods.go
- mods_test.go
> fix: rename --save to --title

- README.md
- examples/conversations.tape
- examples/demo.tape
Updates README GIFs and adds `.tape` files.
> Updated streaming GIFs + conversation GIFs

- main.go
since we now use cobra and can `RunE`, we can improve the error handling in `main.go` too.
Done just that :)
> fix: improve error handling

- .gitignore
- config.go
- db.go
- db_test.go
- go.mod
- go.sum
- main.go
- mods.go
- mods_test.go
- styles.go
- Use Cobra
- Clean up
- Refactor
- shell completions 
- improve performance a bit 
- some ui style improvements
> feat: cobra, shell completions, perf and ui improvements

- config.go
- main.go
- styles.go
- term.go
- exhaust stdin before throwing errors
- delay init of styles et al
> fix: styles init

- mods.go
It seems to not be required anymore.
> refactor: remove clear line once

- main.go
- styles.go
> chore: minor edits to the conversation listing coloring

- README.md
- config.go
- main.go
- mods.go
Implement the show-last flag to show the last conversion, analogous to the continue-last flag.
> feat: --show-last

- mods.go
Seems like the options were there but were never really implemented.
This should fix it.
closes #181
> fix: -p and -P

- config.go
- config_template.yml
also move the config template to a yaml file and embed it, so we have proper syntax highlight and editor support on it.
> feat: add gpt-4-1106-preview and gpt-3.5-turbo-1106

- mods.go
- mods_test.go
This will, when openapi returns the appropriate error, try to estimate how many chars to cut from the prompt instead of defaulting to 10 chars.
It should help preventing many retries erroring and rate limiting as well.
> feat: improve handling of max tokens

- main.go
ask both the prompt and which model to use.
> feat: when no args given, ask to choose model too

- main.go
Small error improvement.
Before:
After:
> feat: cleaner error when the user simply exits huh

- go.mod
- go.sum
Just to grab all the latest improvements added we added for `mods`.
> chore: pin huh to main

- mods.go
> fix: only set completion response format when api is openai

- mods.go
this seems to improve output of mods --show and mods -S
> fix: wrap stdin in codeblock

- README.md
- config.go
- main.go
- mods.go
> feat: allow to set stop

- mods.go
> fix: handle non-existent role

- main.go
This should help debug memory usage problems, such as #211
> feat: add hidden --memprofile

- mods.go
> fix: treat config key "role" as optional

- anthropic.go
- cache.go
- cache_test.go
- go.mod
- go.sum
- mods.go
- ollama.go
> feat(deps): update openai

- main.go
> feat: allow --dirs config|cache

- config.go
- main.go
- mods.go
Will come in handy if you have many roles...
> feat: --list-roles

- config_template.yml
Adding claude-3.5-sonnet-20240620 to config_template.yml.
> config_template.yml += claude-3.5-sonnet-20240620

- README.md
- cohere.go
- config_template.yml
- go.mod
- go.sum
- mods.go
- stream.go
Hello! 👋
Thank you for this nifty project! ❤️
This PR adds support for Cohere's models. Cohere has a [free-tier](https://docs.cohere.com/docs/rate-limits) for experimentation
API Reference: [docs.cohere.com/reference/chat](https://docs.cohere.com/reference/chat)
_Disclaimer:_ I am a Cohere employee experimenting with the product, this is in no way indicates that Cohere will provide official support for Mods.
> feat: add support for Cohere

- mods.go
Just one change: fix the typo that prevents from using personal URL with ollama.
> fix https://github.com/charmbracelet/mods/issues/311

- config_template.yml
Refer: https://community.sambanova.ai/t/supported-models/193
> Add SambaNova Cloud

- config_template.yml
as per https://docs.anthropic.com/en/docs/about-claude/models/all-models
> config_template.yml += claude-sonnet-3.7 support

- config_template.yml
The model has been tested and usable, llama4 is currently the latest available llama model in groq
> feat(config_template.yml): add groq's llama4 to config

- README.md
added environment variable settings to readme for using gemini.
> docs: add googe api key instructions

- config_template.yml
https://www.anthropic.com/news/claude-4
> feat: add sonnet-4 to config template

- config_template.yml
> Add GitHub Models API to config template

- internal/openai/format.go
Fixes https://github.com/charmbracelet/mods/issues/512
Before:
After:
> Fix parameters for openai mcp tool call

- mods.go
- mods_test.go
https://github.com/charmbracelet/mods/issues/506
> random model pick with `--model` fix

- config_template.yml
- add opus 4.1
- add haiku
- remove deprecated models
> fix: update config template adding opus 4.1
