config.go, cyclingchars.go, mods.go
This introduces the `--status-text` and `STATUS_TEXT` argument and environment variable for customizing text displayed in the 'generating' animation. I found myself wanting this feature to provide some extra context to the user when writing scripts with `mods`.
```
$ ./generate-kamojis cat
7&AB%^J_8E Generating cat kamojis...
```
Suggestions on the argument and environment variable naming is welcome.
=> feat: customize text shown in generating animation

config.go
=> fix: print the filename if config is invalid

anim.go
Since releasing Mods we've ported the periods of ellipsis spinner (the three dots in `Generating...`) to [Bubbles](https://github.com/charmbracelet/bubbles). This update switches to the version in Bubbles.
=> chore: use ellipsis spinner ported to Bubbles

README.md
The command shown in the GIF doesn't match the one written out in the readme.
=> fix(readme): pass README.md to stdin in the example

README.md, cache.go, config.go, main.go, mods.go
Adds `--continue`/`-c` to allow continuing the conversation from the last prompt/response.
Stores the most recent conversation in a temp file unless `--no-cache` is specified.
=> feat: add ability to continue, save, and manage conversations

README.md, config.go, mods.go
Various LLM model services may require an HTTP proxy for access. Adding proxy configuration options can avoid the hassle of manually configuring environment variables every time they are used.
If the `HTTPProxy` field is set in the configuration, create an `http.Client` with the specified proxy URL and use it in the `openai.NewClientWithConfig` function.
=> feat: add support for HTTP proxy in the configuration.

config.go, mods.go, mods_test.go, spec.md
added `--continue-last` (or `-C`) to continue the previous conversation without providing a save title
also fixed the behavior of `--continue=id` and `--continue=title` to actually update the previous conversation instead of creating a new one (unless `--save=name` is specified)
=> feat: --continue-last

main.go
outputting the list to stdout allows to easily pipe it into something else (e.g. grep to search).
Not sure what to do with the `Saved conversations` header though... I feel like we can probably remove it 🤔
=> fix: --list should print list to stdout

go.mod, go.sum, main.go, mods.go
This will make mods behave a bit differently when the output is a TTY:
- it'll clear the view (returning `""`) in the end
- then print the content to stdout outside bubbletea loop 
If the output is not a TTY (i.e. `| some_other_prog`), it'll stream as before and do nothing else.
=> fix: render final result

go.mod, go.sum, main.go
- adds the time since the last update in a conversation to the list.
- when pipeing `-l`, use tabs as separatos to allow easier `cut` et al
=> feat: list shows time since

README.md, config.go, main.go
Before this commit, according to the README, `--quiet` should supress all stderr output, which was incorrect. It did what the help says: supress only the spinner.
This commit makes `--quiet` supress all "superflous" stderr ouput, meaning both the spinner and messages that confirm an operation was carried out successfully like "Conversation saved...".
Rationale: for scriptability, it would be nice to be able to supress non-error stderr messages without losing the ability to see the error when something actually goes wrong.
Maybe this isn't the way to do it though, and there should be options for `--no-spinner`, `--quiet` (supress all stderr) and `--shy` (what this commit implements).
=> feat: have --quiet supress all stderr messages for success

mods.go, mods_test.go
If you run `mods` without any args or input, it'll print the help. If you run `mods` with either a prompt or piping something from stdin, it uses that as a prompt.
`mods -C` was requiring a prompt even when it was provided via stdin. This removes that check, so it works the same as `mods` without the `-C` flag now.
closes #132
=> fix: improve --continue

README.md
`mods` installation manifest has been added to [Scoop](https://github.com/ScoopInstaller/Scoop#what-does-scoop-do). See ScoopInstaller/Main#5002.
It is now possible to install/update the latest `mods` version on Windows using
```bash
scoop install mods
```
=> Document `scoop` Windows installation option

config.go, config_template.go, mods.go
Partially addresses #117 `specify api key directly (instead of referencing env var)`.
This PR adds the functionality of setting the API key directly on the settings `mods.yaml` file. If no value is set (which is the default setting), it falls through to the current behavior (env var check and err message if unset). 
The error message was also updated to reflect these changes. Message's up to changes if requested!
No tests were updated as no tests regarding this particular flow were found.
=> feat: adds support to api key on settings mods.yaml

config_template.go
This revision strips the extra leading newline in the config template:
=> fix: drop extra leading newline in config template

mods.go
if the user don't set a title to the convo, it'll use the first line of the prompt.
adding a new line between the prompt and the format text makes sense, as before it could generate strings like `tell a joke format in markdown`.
closes #182
=> fix: do not append formatting prompt to db save title

flag.go, main.go, mods.go
This PR changes #179 a bit:
- only errors if input is not a TTY (reading from STDIN) and the Args+STDIN is empty
- if input is TTY, ask for user input using huh
- fail-fast if user input is whitespace only (e.g. piping an empty file)
- a side-effect of this is that now it'll only show the help if run with `--help`/`-h`
supersedes #179 
closes #179
closes #160
=> fix: handle missing prompt

config.go, config_template.go, config_template.yml, config_test.go, go.mod, go.sum, main.go, mods.go, mods_test.go
Introduce a new flag, `--format-as`.
It defaults to `markdown`, and is only used when `--format` is also specified.
`--format-as=json` will only set the response type to json in supported models, otherwise it'll only add the format text to the prompt.
Also updated the openai library to support this.
Added to the default configuration both `gpt-4-1106-preview` and `gpt-3.5-turbo-1106`. (update: moved to #190)
Theses are the only models that support the JSON response format.
`format-text` is now a `map[string]string`. Old configs (which have it as a string) will set the specified formatting text to the `markdown` format automatically.
Newly generated configs will have both `markdown` and `json` format texts.
---
closes #167
closes #173
=> feat: support json

main.go
the renderer will send sequences to clear screen, hide/show mouse, etc, which will not work if output is not a tty.
fixes #198
fixes #86
=> fix: do not use a renderer if output is not a tty

README.md, main.go
I reckon that everyone will always run `:!mods -q prompt` within vim, so this sets quiet automatically if `$VIMRUNTIME` is not empty, which AFAIK only is true if running within vim/neovim.
---
Clockwise from top left:
- `:terminal` within neovim running `env | rg VIM`
- `:.!env` from neovim
- `env | rg VIM` from terminal
=> fix: set --quiet if running from vim

main.go
=> fix: allow to run --settings with an invalid yaml configuration

mods.go
All errors were citing issues with OpenAI API Key, even if another API endpoint was used. This PR resolves that issue by getting the name of the API used instead of a hard-coded value.
=> fix: include api name in errors

config_template.yml, mods.go
1.  Added [current Perplexity models](https://docs.perplexity.ai/docs/model-cards) to default configuration template.  
2.  Online models were providing low quality responses.  [Perplexity docs](https://docs.perplexity.ai/docs/model-cards#online-llms) state, `It is recommended to use only single-turn conversations and avoid system prompts for the online LLMs (sonar-small-online and sonar-medium-online).`
Experimented, and omitting some of the `ChatCompletionRequest` properties fixes response quality issues for these online models, so added a conditional to mods.go.
Closes #201
=> Add Perplexity API

config_template.yml
Adds support for RunPod and OpenAI compatible Workers.
https://docs.runpod.io/serverless/workers/vllm/openai-compatibility
User must supply their Endpoint by setting it as an env. variable and passing in their model name.
=> Adds support for RunPod

load.go, load_test.go, mods.go
This allows to set a role message to either a http/https URL or a filepath (prefixed with `file://`).
Solves #235
=> feat: allow to use role from URL/filepath

main.go
After copying the conversation ID I was left wondering "what now?", so here's a
PR to include some suggested actions to use the conversation IDs. I kept it
simple, just suggesting the long form usage of the flag as it was taking a bit for
me to figure out how to get specific flags from cobra.
preview:
=> feat(ui): provide suggested use for convo ID

mods.go
it seems its the animation that's causing the memory issues
this makes `--quiet` not instantiate it, so the underlying problem can be avoided while I figure this out.
=> fix: do not create anim internals when --quiet

mods.go
=> fix: high ram usage while loading

config_template.yml
Llama2 has been discontinued by Groq in favour of Llama3. It has a larger context window and also has both 70b and 8b models.
Groq also provides Google Gemma (7b) as well.
Source: https://console.groq.com/docs/models
=> Update Groq Models

config_template.yml
Replace models based on [deprecation notice](https://docs.perplexity.ai/changelog/new-models-llama-3-sonar-family) and [supported model documentation](https://docs.perplexity.ai/docs/model-cards).  
Note, deprecation effective as of May 14.
Closes #259
=> Update perplexity models

config_template.yml
Ref [gpt-4o](https://platform.openai.com/docs/models/gpt-4o)
=> Add OpenAI's new gpt-4o model to default config template

README.md
Several of the headings under settings were inconsistent. Set them to match the depth of the existing settings.
=> fix: Inconsistent markdown headings

stream.go
The Anthropic API doesn't support the `System` prompt, so the `format` and `role` options cause it to fail.
I fixed it by removing the messages with the `System` role and appending their message to the `System` request value instead.
=> Fix issue with Anthropic not supporting the `system` role

main.go
built on top of #281, this registers an autocomplete func for `--role`
=> feat: --role shell completions

README.md
I'm sure it worked at some point, but now winget says there's multiple packages matching "mods" so the full ID is required.
```shell
> winget install mods
Multiple packages found matching input criteria. Please refine the input.
Name        Id                 Source
--------------------------------------
JGC Connect 9NM2X7TGDDWD       msstore
mods        charmbracelet.mods winget
```
but `winget install charmbracelet.mods` works. ✨
=> Fix winget command with full package ID

README.md, main.go, main_test.go
The way it works today, its not possible to install the completions
automatically on Nix, as the build needs to be pure.
This is kinda hacky, but I think it'll work: we only allow the
completion cmd to run if there is good evidence that it is a completion
command, and not a prompt that happens to start with completion.
refs https://github.com/charmbracelet/mods/issues/287
=> fix: improve completion cmd handling 

config.go, examples.go, main.go
The examples we show are only relevant to the root command, so we can show them only in that case.
=> fix: do not show examples in subcommands

config.go, go.mod, go.sum, main.go, main_test.go
add `mods man` so we can generate and package man pages as well.
You can preview it with:
```bash
mods man >mods.1
gzip -c mods.1 >mods.1.gz
man -l mods.1.gz
```
=> fix: add man page

db.go, db_test.go, main.go, mods.go, mods_test.go
this makes `--continue` and `--continue-last` use the same model that was used for the conversation being continued.
before it would simply use the default.
fixes #263
=> feat: continue using the same model

config_template.yml
To make the config consistent among all non-local providers
=> Add api-key and api-key-env fields to config template

config_template.yml
Mistral is known for their open models (originally Mistral 7b, then their Mixtral MoE model), but they also have proprietary models that they're offering through their inference API "La Plateforme": https://docs.mistral.ai/deployment/laplateforme/overview/
The original purely proprietary models (small, medium, large) are not SOTA anymore and might get deprecated at some point, but their latest model "Mistral Large 2" is supposedly close to Llama 3.1 405B (as per https://mistral.ai/news/mistral-large-2407/). (And while not entire proprietary, its weights can only be used under their non-commercial "Mistral Research License", while their platform allows commercial use)
The API is OpenAI-compatible, so `mods` works with it out-of-the-box.
=> Add Mistral provider to config template

mods.go
Fixed an issue where Anthropic base-url configuration did not work.
=> fix: Correct baseURL configuration for Anthropic API

config_template.yml
=> config_template.yml: Add DeepSeek models to template

main.go
=> fix: output correct model if ContinueLast

README.md, anthropic.go, config.go, config_template.yml, google.go, main.go, mods.go, ollama.go, stream.go
This PR uses the same logic implemented to integrate Anthropic to `mods` but for Google's API.
The only weird part of this implementation is handling `system` prompts, which are currently treated as the first `user` message.
I've also fixed some naming issues I encountered throughout the codebase:
- Normalize the usage of the `topk` argument on those providers that support it.
- Fix a bug with the `--format` and `--format-as` options that were not working as expected.
=> Add support for Google Gemini API

main.go, mods.go
the output was being print as part of the bubbletea loop, but it wasn't respecting terminal sizes or anything.
also, in some places, it should have been checking for `--raw` but wasn't.
this pr should fix both issues.
=> fix: raw output being rendered twice

config.go, mods.go, stream.go
In certain OpenAI Azure setups, the `user` parameter is a mandatory filed in the requests. Failing to include it results in a 422 error code. This patch introduces a mechanism to add the user parameter, allowing the use of mods in such setups. 
I would appreciate your feedback on this change and any suggestions for improvement. Thank you!
=> feat: Add support for user request parameter

config.go, config_template.yml, go.mod, go.sum, mods.go
=> feat: api-key-cmd to run command to get API key

main.go
Fixes #299.
_I hope that there are no other parts in the code that should be changed._
To test the change:
```bash
mods -R default "What's up?"
```
1. Run this on the main branch version. This should give the following error:
```
Check out  mods -h  for help.
unknown shorthand flag: 'R' in -R%!(EXTRA string=  )
```
2. Run this on my branch. This should give no errors.
=> feat: add `-R` shorthand to `--role`

config_template.yml, copilot.go, mods.go
Implements GitHub Copilot authentication with a new HTTP HttpClient, including token handling and support for new models.
* [`copilot.go`](diffhunk://#diff-458af75f479d120c6a67cc8de8f4c8488fcdfd0b7175b29191beff1fee01c71dR5-R148): Introduced a new `CopilotHTTPClient` struct to manage HTTP requests and token handling for Copilot, including methods for retrieving and refreshing tokens. This change also includes defining constants for the Copilot authentication URL, editor version, and user-agent.
* [`mods.go`](diffhunk://#diff-d92d2fa2f22fc443e1ae12da3fc2e8556aa5e643eb96c0f72c013ea3b43495e5L360-R370): Updated the `startCompletionCmd` function to use the new `CopilotHTTPClient` for authentication, replacing the previous method of sending the RefreshToken to the API. This ensures that the …
=> feat(copilot): improved support for AccessToken and Enterprise API

config_template.yml
This pull request includes changes to the `config_template.yml` file to update the API configurations. The most important changes involve adding a new API configuration and modifying existing aliases.
API configuration updates:
* Added a new API configuration for `o3-mini` with aliases `["o3m", "o3-mini"]` and a maximum input character limit of 128000.
* Removed the `o1-mini-2024-09-12` API configuration and updated the aliases for `o1-mini` to include `["o1-mini", "o1m", "o1-mini-2024-09-12"]` with a maximum input character limit of 128000.
=> feat(config): add o3-mini model and update model aliases

config_template.yml
For now, it is necessary to enable the model in your GitHub config. Otherwise, it will say you don't have permission to use the model.
You can find this option under "Settings > Copilot" (https://github.com/settings/copilot).
> ![Screenshot_2025-02-07_20-30-27](https://github.com/user-attachments/assets/734b33f1-eb24-4647-9f34-c46d5a125778)
**GitHub Announcement**
https://github.blog/changelog/2025-02-05-google-gemini-2-0-flash-is-now-available-to-all-copilot-users-in-public-preview/
**Google Models reference API**
https://ai.google.dev/gemini-api/docs/models/gemini
**Request**
=> feat(config): add gemini-2-flash models and update aliases

config_template.yml
=> fix: update deepseek in config template

config_template.yml
1. Reset your settings using the command `mods --reset-settings`. 
Then subsequent commands should be met with the following error:
1. Removed the duplicate `o3-mini` key
2. Replaced the duplicate alias `o1-preview` from the o1 model with just `o1`
3. Updated the max-input-chars for `o3-mini` from `128000` to the correct value `200000` per OpenAI docs
=> fix: remove duplicate model key `o3-mini` from config template

stream.go
This fix maintains compatibility with legacy o1 models while solving the Perplexity error.
A previous update (commit e5e4bdd) added support for o1-preview and o1-mini models by converting system messages to user messages. However, this breaks Perplexity models because their API doesn't allow multiple consecutive messages with the same role.
Try this command and you'll see an error:
```
mods --model llama-3.1-sonar-small-128k-online --role shell list all files
```
- Only remap system messages for the two models that need it (o1-preview and o1-mini)
- Keep the original message roles for all other models that go through the function `createOpenAIStream (stream.go)`
The system message remapping is not needed for these models, which handle system messages correctly without modification:
- o1
- …
=> Fix Perplexity API Role Compatibility (Issue #448)

mods.go
Removing the final ending dot because it it really appended to the link when on hover open it.
=> fix: remove final dot to fix link to grab api key

config_template.yml
The Ollama API already add a /api.
=> mod config_template.yml to remove api/ as it is already used in ollama api call

config.go, main.go
closes #549
make sure the `CACHE/conversations` dir is created as well
=> fix: mkdir parent db directory
